title: KiSung's Blog
email: your-email@example.com
description: >-
  개발과 일상을 기록하는 블로그입니다.
baseurl: ""
url: "https://kisungsheen.github.io"
twitter_username: your_username
github_username: kisungsheen

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/